[package]
# productName = "test"
version = "0.0.1"

[build]
devPath = "www"
distDir = "www"
withGlobalTauri = true

[tauri.allowlist]
all = true

[tauri.allowlist.shell]
all = true
open = true


[[tauri.windows]]
fullscreen = false
height = 600
resizable = true
title = "nmud"
width = 800


# [tauri.updater]
# active = false

# [tauri.bundle]
# active = true
# category = "DeveloperTool"
# copyright = ""
# externalBin = []
# icon = [
#     "icons/32x32.png",
#     "icons/128x128.png",
#     "icons/128x128@2x.png",
#     "icons/icon.icns",
#     "icons/icon.ico",
# ]
# identifier = "com.tauri.release"
# longDescription = ""
# resources = []
# shortDescription = ""
# targets = "all"

# [tauri.bundle.windows]
# digestAlgorithm = "sha256"
# timestampUrl = ""

# [tauri.bundle.windows.webviewInstallMode]
# type = "downloadBootstrapper"
